CONFIG = {
    "BUFFER_KEEP_MS": 4000,
    "WINDOW_DURATIONS_MS": [300, 500, 800, 1200, 1600, 2200],
    "MIN_SPAN_MS": 250,
    "MAX_SPAN_MS": 2500,
    "MIN_FRAME_COUNT": 3,
    "MAX_UNKNOWN_RATIO": 0.65,
    "FIELD_WEIGHTS": {
        "hand_count": 2.0,
        "movement": 2.2,
        "relative_motion": 1.9,
        "location": 0.6,
        "bimanual_relation": 1.5,
        "dominant_shape": 0.8,
        "nondominant_shape": 0.5,
        "dominant_side": 0.0,
    },
    "STAY_BONUS": 0.02,
    "ADVANCE_PENALTY": 0.05,
    "MIN_STEP_FRAMES": 2,
    "WIDE_FILTER_MAX_CONFLICTS": 1,
    "WIDE_FILTER_TOP_N": 153,
    "PENDING_SCORE_THRESHOLD": 0.58,
    "CONFIRM_SCORE_THRESHOLD": 0.72,
    "TOP_MARGIN_THRESHOLD": 0.015,
    "STABLE_N": 3,
    "OVERLAP_IOU_THRESHOLD": 0.50,
    "COOLDOWN_MS": 600,
    "SAME_WORD_SUPPRESS_MS": 1000,
}

